version: 2.1

jobs:
  fake-unit-tests:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run:
          name: cat README
          command: cat README.md

workflows:
  my-workflow:
    jobs:
      - fake-unit-tests
