version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint

  build:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  test:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout
      - run: npm ci
      - run: npm run test

  deploy:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - attach_workspace:
          at: .
      - run: echo "Pushing to production..."

workflows:
  Build & Deploy:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - build
      - deploy:
          requires:
            - test
            - build
