version: 2.1

jobs:
  install:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  test:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run tests
          command: npm test
      - store_test_results:
          path: junit.xml

workflows:
  install-and-test:
    jobs:
      - install
      - test:
          requires:
            - install
