version: 2.1

jobs:
  job1:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run:
          name: cat README
          command: cat README.md

workflows:
  github-app-workflow:
    jobs:
      - job1
