version: 2.1

orbs:
  jq: circleci/jq@3.0.2
  
jobs:
  myjob:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - jq/install
      - run:
          name: "Extract webhook properties"
          command: |
            EVENT_ACTION=$(echo '<< pipeline.trigger_parameters.webhook.body >>' | jq '.action')
            EVENT_BRANCH=$(echo '<< pipeline.trigger_parameters.webhook.body >>' | jq '.pull_request.head.ref')
            echo "Action is: $EVENT_ACTION"
            echo "Branch is: $EVENT_BRANCH"
      
workflows:
  do_some_stuff:
    jobs:
      - myjob
