version: 2.1

orbs:
  jq: circleci/jq@3.0.2
  
jobs:
  myjob:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - jq/install
      - run:
          name: "Print event action (1)"
          environment:
            WEBHOOK_BODY: << pipeline.trigger_parameters.webhook.body >>
            EVENT_ACTION: echo $WEBHOOK_BODY | jq '.payload.action'

          command: echo "$EVENT_ACTION"
workflows:
  do_some_stuff:
    jobs:
      - myjob
