version: 2.1

orbs:
  jq: circleci/jq@3.0.2
  
jobs:
  myjob:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - jq/install
      - run:
          name: "Print event action"
          environment:
            EVENT_ACTION: << pipeline.trigger_parameters.webhook.body >> | jq '.payload.action'
          command: echo $EVENT_ACTION

workflows:
  do_some_stuff:
    jobs:
      - myjob
