version: 2.1

orbs:
  jq: circleci/jq@3.0.2
  
jobs:
  myjob:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - jq/install
      - run:
          name: "Print event action (1)"
          environment:
            EVENT_ACTION: echo << pipeline.trigger_parameters.webhook.body >> | jq '.payload.action'
          command: echo $EVENT_ACTION
      # - run:
      #     name: "Print event action (2)"
      #   #   command: |
      #   # echo 'export EVENT_ACTION=/path/to/foo/bin:"$PATH"' >> "$BASH_ENV"
      #   # echo "export VERY_IMPORTANT=VALUE_CONTENT" >> "$BASH_ENV"
      #   # source "$BASH_ENV"        

workflows:
  do_some_stuff:
    jobs:
      - myjob
