pipeline:
  identifier: Build_BeFunes_demo_fake_1713202908668
  name: Build demo-fake
  orgIdentifier: default
  projectIdentifier: myproject
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1712833751630
        repoName: BeFunes/demo-fake
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
    - stage:
        name: pp
        identifier: pp
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: popo
                  identifier: popo
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
              - step:
                  type: Email
                  name: Email_1
                  identifier: Email_1
                  spec:
                    to: benedetta.dalcanton@gmail.com
                    cc: ""
                    subject: pop
                    body: ""
                  timeout: 10m
        tags: {}
